Style/Tab:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Style/AccessModifierIndentation:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/IndentArray:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
