Style/Tab:
  Enabled: false
Style/IndentationWidth:
  Width: 1

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Style/SymbolProc:
  Exclude:
    # Bug in Ruby 2.3: https://bugs.ruby-lang.org/issues/12638
    - 'lib/gorilla-patch/deep_dup.rb'

Style/FileName:
  Exclude:
    # Consistency of naming
    - '**/gorilla-patch*'
